version: '3.3'
services:
  text_2_image:
    image: text2image:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1', '2']
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=1,2
    stdin_open: true
    tty: true
    network_mode: host
